#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

use BMM\CMSMove\Console\Start;
use BMM\CMSMove\Console\Push;
use BMM\CMSMove\Console\Pull;

require __DIR__.'/vendor/autoload.php';

$app = new Application('CMS Move', '@package_version@');
$app->add(new Start);
$app->add(new Push);
$app->add(new Pull);
$app->run();